### ISSUE TITLE
attg_card_hand not working

### ISSUE THREAD

**Issue by Meibisu** [ALLTHETIMEGAMING/ATTG-Plugin#3]
attg_card_hand: false is not working in config_gameplay.txt. Players still can open doors with card in inventory.

**Comment by ALLTHETIMEGAMING** [comment]
I will look in to the error

**Comment by ALLTHETIMEGAMING** [comment]
I have fixed the error and it will be in the next update

**Comment by ALLTHETIMEGAMING** [comment]
REEEEEEEEEEEEEEEEEEEEE
